language: python
repo_token: pS7mNOOFu5EF5MxxMIS0V0MzopVg5rLEN
python:
  - "3.6"
install:
  - pip install python-coveralls
# command to run tests
script: make test
after_success:
  - coveralls